export type { AIProvider, SynthesisInput, SynthesisOutput, RestaurantCandidate, ProposalOutput } from './interface';
export { ClaudeAIProvider } from './adapters/claude';
export { buildSynthesisPrompt } from './prompts/restaurant-synthesis';
export { runPipeline } from './pipeline/orchestrator';
export type { PipelineResult, PipelineStage, ImplicitContext, StructuredConstraint, RestaurantScore, EnvyScore, ProposalWithNarrative } from './pipeline/types';
export { PipelineError } from './pipeline/types';
export { logStage, safeLogStage } from './utils/logger';
export { computeCostMicros } from './utils/cost-tracker';
export { getCachedRestaurant, setCachedRestaurant } from './utils/cache';
export type { RestaurantCacheRow } from './utils/cache';
export type { ConstraintStrength, ConstraintItem, ImplicitInferenceResult } from './pipeline/types';
export type { DataSource, DietarySignal, DietaryAnalysis, EnrichedCandidate } from './pipeline/types';
export { geminiMapsGrounding, geminiAdapter } from './adapters/gemini';
export { enrich as menuPhantomEnrich, menuPhantom } from './stages/menu-phantom';
export { score as deterministicScore, deterministicScorer } from './stages/deterministic-scorer';
export { run as vibeEmbedderRun, vibeEmbedder } from './stages/vibe-embedder';
export { run as rerankerRun, reranker } from './stages/reranker';
export { run as fairnessCheckerRun, fairnessChecker } from './stages/fairness-checker';
export { run as reasoningEngineRun, reasoningEngine } from './stages/reasoning-engine';
export { run as criticVerifierRun, criticVerifier } from './stages/critic-verifier';
export { run as narrativeGeneratorRun, narrativeGenerator } from './stages/narrative-generator';
export type { CandidateDetail } from './pipeline/types';
export type { EventDataLoader, LoadedEventData, EventDataRecord } from './pipeline/orchestrator';
